### PR TITLE
Resolved issues #172 #173

### PR DESCRIPTION
**Pull request by toubou91**

### CODE REVIEW

**Comment by vkarampinis** [comment]
@toubou91 tnx :+1:

**Comment by toubou91** [comment]
@vkarampinis no prob, more than happy to contribute :smiley: :

**Comment by margaritis** [comment]
Resolves #172

**Comment by margaritis** [comment]
:+1: @toubou91

**Comment by ntemposd** [comment]
@toubou91 FTW! :tada: :tada:

**Pull request merged**
