### PR TITLE
Update Evolving React Patterns workshop

### PR DESCRIPTION
**Pull request by sirodoht**

### CODE REVIEW

**Comment by kbariotis** [comment]
View your PR here .

**Comment by sirodoht** [comment]
@kbariotis Something seems to be missing 😝

**Comment by kbariotis** [comment]
@sirodoht that's odd. Can you please rerun the build?

**Comment by kbariotis** [comment]
View your PR here .

**Comment by kbariotis** [comment]
Yeah sorry check to see if you can debug it otherwise will check it once I get home.

**Comment by sirodoht** [comment]
@kbariotis Is it fixed?

**Comment by kbariotis** [comment]
@sirodoht it seems like your master was behind. Can you rebase with master and push again please?

**Comment by kbariotis** [comment]
View your PR here .

**Pull request merged**
