### PR TITLE
Workable premium sponsor

### LINKED ISSUE #165: Add workable as Premium Sponsor
Point to their base website: https://www.workable.com/

We have the logo in open pdf, needs a conversion to png, find it in [drive 2016/sponsors/logos/02 Premium/workable](https://drive.google.com/drive/u/0/folders/0B68iSVdp87MFMjdBTmczb3RSV1E).

### PR DESCRIPTION
**Pull request by modkaffes**
Resolves #165

### CODE REVIEW

**Comment by vkarampinis** [comment]
I think its a bit ugly to have 3 at the same row and 1 below. Maybe 2-2 its better.

What do you think?


screen shot 2016-03-22 at 11 50 38

**Comment by modkaffes** [comment]
Yes, nice touch 👍

**Comment by thanpolas** [comment]
ready to merge?

**Comment by modkaffes** [comment]
@thanpolas yes.

**Comment by thanpolas** [comment]
@vkarampinis please merge and deploy

**Pull request merged**
