### PR TITLE
Pixel try two

### PR DESCRIPTION
**Pull request by thanpolas**
This reverts commit f7a1cfac26fd63a0e468c465eaaa222020711c20.

### CODE REVIEW

**Comment by thanpolas** [comment]
@kbariotis i need a hand here... I don't know what to do with CI, htmlproof passes on my local and everything works... When i merged this and deployed the site broke with a JS error on the `commons.js` file (!?!?)... I've run out of ideas and time, please help

**Comment by kbariotis** [comment]
@thanpolas is this is an issue? what are you trying to do?

**Comment by thanpolas** [comment]
@kbariotis i'm trying to install pixel but i keep failing :( read my comment above and please try to deploy this yourself

**Comment by kbariotis** [comment]
@thanpolas by requiring the `metrics.js` file in the `commons.js` file will be loaded on every page. Please review. :)

**Pull request merged**
