### PR TITLE
add venue information for DEVit 2019

### PR DESCRIPTION
**Pull request by varemenos**

### CODE REVIEW

**Comment by kbariotis** [comment]
View your PR here .

**Comment by varemenos** [comment]
@kbariotis Could we add one extra (dark/blue) block between venue and speakers? Currently it looks a bit odd because of the uneven whitespace between them (check staging).

**Comment by kbariotis** [comment]
@varemenos current design I believe follows the templates on Zeplin. Check them.

Also, can you please add the venue on the footer menu?

**Comment by kbariotis** [comment]
View your PR here .

**Comment by kbariotis** [comment]
View your PR here .

**Pull request merged**
