### PR TITLE
Fixed gift error caused by gulp deploy

### PR DESCRIPTION
**Pull request by alexspyr**
When tried to do 'gulp deploy' gift caused an error ( https://github.com/notatestuser/gift/issues/96 ) and I solved it by deleting the gift folder and installing gift again.

### CODE REVIEW

**Comment by kbariotis** [comment]
Im not sure if that will really solve the issue, cause it needs a certain version of gift to be installed every time. Will try this locally.

**Comment by kbariotis** [comment]
It's also related with https://github.com/shinnn/gulp-gh-pages/issues/116.

**Comment by varemenos** [comment]
Is this PR still relevant? Should we close it?

**Comment by kbariotis** [comment]
Closing this, we have moved to using gh-pages directly.

**Pull request closed without merging**
