### PR TITLE
Workshops/Talks lists

### PR DESCRIPTION
**Pull request by kbariotis**

### CODE REVIEW

**Comment by kbariotis** [comment]
View your PR here http://5adca623b312743111ba3dc7.vigorous-wilson-121bb5.netlify.com.

**Comment by kbariotis** [comment]
View your PR here http://5adcaceedd6a544c72b0d154.vigorous-wilson-121bb5.netlify.com.

**Comment by kbariotis** [comment]
@modkaffes That should be fine for the Workshops/Talks list: http://5adcaceedd6a544c72b0d154.vigorous-wilson-121bb5.netlify.com/workshops. The schedule is being worked on the #386 PR. :)

**Comment by kbariotis** [comment]
Btw @modkaffes I don't like adding arbitrary `flex-box` rules to individual blocks since all of our layout is based on bootstrap3 and that suits best for quickly creating blocks with inherited styles by other blocks. We should better consider moving to bootstrap4 and enforce flex-box everywhere. Is this something you would like to work on?

**Comment by kbariotis** [comment]
View your PR here http://5add0748e39e7c5f3eb34c5a.vigorous-wilson-121bb5.netlify.com.

**Comment by modkaffes** [comment]
@kbariotis to be frank, lately it seems to me that it’s easier to avoid bs styles because a) they need to be properly configured through vars in order to be reusable, and b) there’s so much stuff you don’t need. For example, in our original designs, main margin/padding measure comes in multiples of 8 and in order to faithfully replicate the design we have to replace the !default variable values with our own, and so forth.

On the other hand, if we componentize our elements (eg. a schedule/workshop item), we can style them directly using modern styles, and not having to override bs. So, if there’s something I would be interested in working on, it would be to componentize all reusable elements, instead of reapplying a huge library only to use some layout system.

What do you think?

**Comment by kbariotis** [comment]
View your PR here .

**Comment by kbariotis** [comment]
View your PR here .

**Comment by kbariotis** [comment]
View your PR here http://5af1b68a3672df63d470d9fb.devitconf.netlify.com.

**Pull request merged**
